[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hist"
version = "0.1.0"
requires-python = ">=3.9"

[project.scripts]
hist = "hist.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["hist*"]
